spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ecommerce
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  devtools:
    livereload:
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
